### ISSUE TITLE
[Help] Error parsing app.config when using custom-properties in the config file of apimanager-swagger-promote

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apimanager-swagger-promote#122]
**Swagger-Promote Version** : 1.6.0
**API-Manager and Service-Pack Version**: 7.6.2 SP3
**Test case sample**
> Please describe the steps you have done to replicate the issue

Here are the two files used : app.config_ko.txt is the original one that generate the error.
The second one is the workaround, we just added the double quote.

[app.config_ko.txt](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3486254/app.config_ko.txt)
[app.config_ok.txt](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3486255/app.config_ok.txt)

`./run-swagger-import.sh -a /tmp/Delivery_APIM/api-manager-swagger/swagger_complexe.json -c /tmp/Delivery_APIM/api-manager-swagger/conf/config.json -h f4slsea010 -port ${apimngr_port} -u ${apimngr_user} -p ${apimngr_pwd} quotaMode=replace`
```
------------------------------------------------------------------------
API-Manager Promote Version: 1.6.0

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote
------------------------------------------------------------------------

0      INFO  nvironmentProperties| Trying to load environment properties from file: env.pr
1574   INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: '/tmp/
1670   INFO          APIDefintion| Replacing existing host: 'sandbox-api.aife.economie.gou
1737   ERROR                  App| Can't parse API-Manager app.config.
com.axway.apim.lib.AppException: Can't parse API-Manager app.config.
        at com.axway.apim.swagger.APIManagerAdapter.parseAppConfig(APIManagerAdapter.java:
        at com.axway.apim.swagger.APIManagerAdapter.getCustomPropertiesConfig(APIManagerAd
        at com.axway.apim.swagger.APIImportConfigAdapter.validateCustomProperties(APIImpor
        at com.axway.apim.swagger.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdap
        at com.axway.apim.App.run(App.java:177)
        at com.axway.apim.App.main(App.java:44)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}' (code
 at [Source: (String)" {
       user: {
         newsletter:{
            label:'newsletter',
         },
        date_consentement_newsletter:{
            label:'Date consentement newsletter',
        },
        satisfaction: {
            label:'satisfaction',
         },
        date_consentement_enquete:{
            label:'Date consentement enquÃªte',
        },
        consentement: {
            label:'Consentement CGU',
            permissions: {
                admin: { read: true, write: true},
                oadmin: { read: false, write:"[truncated 1176 chars]; line: 5, column: 11]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBas
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserM
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBase
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBased
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonN
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonN
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2551)
        at com.axway.apim.swagger.APIManagerAdapter.parseAppConfig(APIManagerAdapter.java:
        ... 5 more
```

**Comment by Rennaud** [comment]
sorry, I put the same files. Here is the one that works.
[app.config_ok.txt](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3486316/app.config_ok.txt)

**Comment by cwiechmann** [comment]
@Rennaud, the primary reason why the app.config parser couldn't parse the config file are the additional commas where no commas are allowed. A few examples:
![image](https://user-images.githubusercontent.com/16292002/62793717-8348de00-bad2-11e9-927b-b8ea538c68d6.png)
When the section is closed, commas aren't allowed. In the unit-test I removed the commas and it's working.
