### ISSUE TITLE
[BUG] ERROR APIDefintion| Cannot replace host in provided Swagger-File. Continue with given host.

### ISSUE THREAD

**Issue by ua-sopra-steria** [Axway-API-Management-Plus/apimanager-swagger-promote#140]
**Swagger-Promote Version**
1.6.1-1

**API-Manager and Service-Pack Version**
7.7 SP1

**Expected behavior**
When importing an API definition and also setting the parameter backendBasepath, then according to the documentation the host parameter in the Swagger file should be replaced.

**Actual behavior**
We receive the following error:
```
1698   ERROR         APIDefintion| Cannot replace host in provided Swagger-File. Continue with given host.
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'swagger': was expecting ('true', 'false' or 'null')
 at [Source: (byte[])"?swagger: '2.0'
info:
    title: Company API
    version: 1.1.0
host: 'my.domain.local'
basePath: /dk/psd2/v1
schemes:
    - https
paths:
    /accounts:
        get:
            summary: Get all accounts
            description: Get all accounts for logged-in user
            operationId: getAccounts
            produces:
                - application/json
            parameters: []
            responses:
                '200':
                    description: Succe"[truncated 1896 bytes]; line: 1, column: 9]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3532)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2627)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:832)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:729)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4043)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2572)
        at com.axway.apim.swagger.api.properties.APIDefintion.setAPIDefinitionContent(APIDefintion.java:51)
        at com.axway.apim.swagger.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:175)
        at com.axway.apim.App.run(App.java:181)
        at com.axway.apim.App.main(App.java:44)
```
We can get rid of the error by setting the following parameter in the environment file:
`replaceHostInSwagger=false`
But then the host is not replaced.

**Test case sample**
To see the error execute the following command:
`scripts\run-swagger-import.bat -c samples\test\contract-test.json`

API definition and contract definition can be found in the attached file.

[contract-test.zip](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3568322/contract-test.zip)

**Comment by cwiechmann** [comment]
@ua-sopra-steria, Swagger-Promote doesn't support YAML-Swagger files today, even if the API-Manager 7.7 supports it. Hence, I'm afraid as of today you to convert into JSON.

**Comment by cwiechmann** [comment]
Created a project to keep track of this requirement:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/projects/2
