### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by OlivierWintquin** [Axway-API-Management-Plus/apimanager-swagger-promote#150]
![APIGW_AfterImport](https://user-images.githubusercontent.com/55444776/65046888-ba2bd280-d961-11e9-8f29-ab8583272e1b.JPG)

**Swagger-Promote Version**
API-Manager Promote Version: 1.6.1-1

**API-Manager and Service-Pack Version**
API-Manager version is: 7.5.3 SP7

**Question**
When using swagger-promote, I have an issue when loading a .p12 certificate. No error message at deployment but the result gives a field in error on the API Manager, as you can see in the attached file.
configuration-fragment : 
  "authenticationProfiles": [
    {
      "name": "_default",
      "isDefault": "true",
      "parameters": {
        "source": "file",
        "certFile": "../../certificatesRepository/oli-server.p12",
        "password": "changeme",
        "trustAll": true
      },
      "type": "ssl"
    }
  ],

**What I've tried so far**
I have tried to export the key and certificate in an not-crypted format (.pem), with no password but then I face following issue : 
com.axway.apim.lib.AppException: Cannot validate/fulfill configuration file.
        at com.axway.apim.swagger.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:191)
        at com.axway.apim.App.run(App.java:181)
        at com.axway.apim.App.main(App.java:44)
Caused by: com.axway.apim.lib.AppException: Can't read Client-Cert-File: ../../certificatesRepository/oli-server.pem from filesystem or classpath.
        at com.axway.apim.swagger.APIImportConfigAdapter.handleOutboundSSLAuthN(APIImportConfigAdapter.java:764)
        at com.axway.apim.swagger.APIImportConfigAdapter.validateOutboundAuthN(APIImportConfigAdapter.java:715)
        at com.axway.apim.swagger.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:180)
        ... 2 more
Caused by: java.security.KeyStoreException: Uninitialized keystore
        at java.security.KeyStore.aliases(Unknown Source)
        at com.axway.apim.swagger.APIImportConfigAdapter.handleOutboundSSLAuthN(APIImportConfigAdapter.java:752)
        ... 4 more

**Additional information**

**Comment by cwiechmann** [comment]
This issue: #147 has been reported before and will be officially fixed with the next version: 1.6.3

If you want you download the attached 16.3-SNAPSHOT from the thread.
