### ISSUE TITLE
[BUG] api-export fails on 7.7 SP1

### ISSUE THREAD

**Issue by wsalembi** [Axway-API-Management-Plus/apimanager-swagger-promote#151]
**Swagger-Promote Version**
1.6.2

**API-Manager and Service-Pack Version**
7.7 SP1

**Expected behavior**
Export succeeded

**Actual behavior**
```
3384   ERROR            ExportApp| Can't read app.config from API-Manager: '<p>Please Login</p>'
com.axway.apim.lib.AppException: Can't read app.config from API-Manager: '<p>Please Login</p>'
        at com.axway.apim.swagger.APIManagerAdapter.getCustomPropertiesConfig(APIManagerAdapter.java:1014)
        at com.axway.apim.api.export.APIExportConfigAdapter.handleCustomProperties(APIExportConfigAdapter.java:184)
        at com.axway.apim.api.export.APIExportConfigAdapter.getAPIsToExport(APIExportConfigAdapter.java:73)
        at com.axway.apim.api.export.APIExportConfigAdapter.exportAPIs(APIExportConfigAdapter.java:57)
        at com.axway.apim.ExportApp.run(ExportApp.java:124)
        at com.axway.apim.ExportApp.main(ExportApp.java:35)
Caused by: com.axway.apim.lib.AppException: Can't parse API-Manager app.config.
        at com.axway.apim.swagger.APIManagerAdapter.parseAppConfig(APIManagerAdapter.java:1036)
        at com.axway.apim.swagger.APIManagerAdapter.getCustomPropertiesConfig(APIManagerAdapter.java:1012)
        ... 5 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -23
        at java.lang.String.substring(String.java:1967)
        at com.axway.apim.swagger.APIManagerAdapter.parseAppConfig(APIManagerAdapter.java:1029)
        ... 6 more
```
**Test case sample**
> Please describe the steps you have done to replicate the issue

api-export -h host -port 443 -l /tmp/apiexport -a /myapi/v1 -u apiadmin -p changeme

**Comment by cwiechmann** [comment]
@wsalembi, looks like a change on version 7.7 SP1. As a first step I have added 7.7 SP1 into the Test-Framework. Let's see what happens.

**Comment by cwiechmann** [comment]
There were some changes required for 7.7 SP1, but in general it's working.

**Comment by cwiechmann** [comment]
@wsalembi, can you please retry with the latest version 1.6.3 and let me know?
