### ISSUE TITLE
[BUG] 7.5.3 SP7 Image issue on export

### ISSUE THREAD

**Issue by shan916** [Axway-API-Management-Plus/apimanager-swagger-promote#184]
**Swagger-Promote Version**
1.6.3-1

**API-Manager and Service-Pack Version**
7.5.3 SP7

**Expected behavior**
When exporting an API without an image from API Manager 7.5.3 SP7, the export should be successful.

**Actual behavior**
```
3803   ERROR            ExportApp| Can't initialize API-Manager API-State.
com.axway.apim.lib.AppException: Can't initialize API-Manager API-State.
	at com.axway.apim.swagger.APIManagerAdapter.getAPIManagerAPI(APIManagerAdapter.java:400)
	at com.axway.apim.api.export.APIExportConfigAdapter.getAPIsToExport(APIExportConfigAdapter.java:73)
	at com.axway.apim.api.export.APIExportConfigAdapter.exportAPIs(APIExportConfigAdapter.java:58)
	at com.axway.apim.ExportApp.run(ExportApp.java:128)
	at com.axway.apim.ExportApp.main(ExportApp.java:35)
Caused by: com.axway.apim.lib.AppException: Can't read Image from API-Manager.
	at com.axway.apim.swagger.APIManagerAdapter.getAPIImageFromAPIM(APIManagerAdapter.java:856)
	at com.axway.apim.swagger.APIManagerAdapter.getAPIManagerAPI(APIManagerAdapter.java:377)
	... 4 more
Caused by: java.lang.NullPointerException
	at com.axway.apim.swagger.APIManagerAdapter.getAPIImageFromAPIM(APIManagerAdapter.java:847)
	... 5 more
```

**Test case sample**
In API Manager 7.5.3 SP7, some APIs that have no image, for some reason show any empty image in the API Catalog in API Manager. See screenshot.

![image](https://user-images.githubusercontent.com/4755022/67054646-1ec18500-f0fa-11e9-961e-4bac66d3e2c1.png)

When I do an API export I can see an image URL in the DAT file instead of a `null` value for the image. When you follow the URL, you get a HTTP 204 without a response body.

The issue is in APIManagerAdapter::getAPIImageFromAPIM on line 847. It is trying to get the content from the entity, but the entity is null `httpResponse.getEntity().getContent();`

**Comment by cwiechmann** [comment]
Fixed with release 1.6.3-2
