### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by OlivierWintquin** [Axway-API-Management-Plus/apimanager-swagger-promote#243]
**Swagger-Promote Version**
1.6.3-SNAPSHOT

**API-Manager and Service-Pack Version**
7.5.3-SP12

**Question**
I try desesperately to configure SSL-MA outbound authentication with my back-end implementation.

**What I've tried so far**
use .p12, .pfx, .jks in configuration, with or without :PKCS12 or :JKS forced certificate type recognition.
the file contains full path of certificates, and I trust them all.
once the certificate is uploaded in one type, the other deployments with other types makes the deployment not happen anymore because the apimanager-swagger-promote does not see any difference with deployed API.
When I re-import the certificate file in API Manager (.p12), afterwards, the first time the certificate is redeployed because the API configuration does not match the apimanager-swagger-promote configuration (apimanager-swagger-promote see changes between its configuration ang the apiManager configuration). 

**Additional information**
Whatever the type of certificate I give, the result is the same : no outbound authentication is possible.
When I import the same certificate file (p12) in API manager for this API, it works fine.

**Comment by cwiechmann** [comment]
Hi @OlivierWintquin, could you please try to replicate the issue on the most recent release 1.6.5?

**Comment by cwiechmann** [comment]
Hi @OlivierWintquin, Do you had the chance to test the use case with version 1.6.5? If yes, can you please give feedback or I'm going to close this issue.

**Comment by OlivierWintquin** [comment]
Hi @cwiechmann .
I had the opportunity to check with version 1.6.5 but it gave exactly the same results.
So, when deploying using SSL Client certificate for backend authentication, whatever the type of certificate (JKS, P12, ...) the configuration is wrong - but the deployment tool says that everything is fine, no error. 
I have then to go to the API manager and re-import the client certificate from there.
When redeploying the policies on a non-redeployed API Manager (through the node projdeploy tool) , I have this error meaning that the API SSL Client certificate and private key are wrong 

      ERROR  10/Mar/2020:10:10:28.296 Error configuring client certificate for API: 
java.lang.RuntimeException: no native proxy for java object 0x7f1e1db15b90
	at com.vordel.security.openssl.PKCS12.decryptN(Native Method)
	at com.vordel.security.openssl.PKCS12.decrypt(PKCS12.java:51)
	at com.vordel.apiportal.runtime.virtualized.CertificateConfig.setClientCertificate(CertificateConfig.java:135)
	at com.vordel.apiportal.runtime.virtualized.MethodConfigFactory.addRoutingProcessor(MethodConfigFactory.java:292)
	at com.vordel.apiportal.runtime.virtualized.MethodConfigFactory.configureCircuit(MethodConfigFactory.java:194)
	at com.vordel.apiportal.runtime.virtualized.MethodConfigFactory.createMethod(MethodConfigFactory.java:100)
	at com.vordel.apiportal.runtime.virtualized.VRuntimeConfigFactory.createMethod(VRuntimeConfigFactory.java:24)
	at com.vordel.apiportal.runtime.virtualized.VApiRuntime.resetFromKps(VApiRuntime.java:186)
	at com.vordel.apiportal.runtime.virtualized.VApiRuntime.init(VApiRuntime.java:129)
	at com.vordel.apiportal.runtime.virtualized.VApiRuntime.<init>(VApiRuntime.java:76)
	at com.vordel.apiportal.runtime.virtualized.VApiRuntimeCache.addVApiToCache(VApiRuntimeCache.java:247)
	at com.vordel.apiportal.runtime.virtualized.VApiRuntimeCache.lambda$initialize$0(VApiRuntimeCache.java:72)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870)
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467)
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:650)
	at com.vordel.apiportal.runtime.virtualized.VApiRuntimeCache.initialize(VApiRuntimeCache.java:70)
	at com.vordel.apiportal.runtime.virtualized.VApiRuntimeCache.<init>(VApiRuntimeCache.java:63)
	at com.vordel.apiportal.runtime.PortalBroker.configure(PortalBroker.java:64)
	at com.vordel.dwe.NativeModule.configure(NativeModule.java:149)
	at com.vordel.dwe.NativeModule.configure(NativeModule.java:63)
	at com.vordel.precipitate.SolutionPack$ConfigModule.configure(SolutionPack.java:297)
	at com.vordel.precipitate.SolutionPack.loadModules(SolutionPack.java:417)
	at com.vordel.dwe.Service.refresh(Service.java:452)
	at com.vordel.api.configuration.ConfigurationService.updateConfiguration(ConfigurationService.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)

**Comment by cwiechmann** [comment]
Can you please share your API-Config-File you are using to deploy the API? (You may omit passwords or any other confidential information)

**Comment by cwiechmann** [comment]
Closed due to inactivity. @OlivierWintquin, please re-open this issue, if the problem remains.
