### ISSUE TITLE
[Feature] On level DEBUG - A lot Warning-Exceptions

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apimanager-swagger-promote#247]
**User story**
With version 1.6.5, when running Swagger-Promote on level DEBUG you see the following Exception:
```
2353   DEBUG    APIManagerAdapter| API-Manager version: '7.5.3 SP12' seems not to contain a dated version
java.text.ParseException: Unparseable date: "3"
        at java.text.DateFormat.parse(Unknown Source)
        at com.axway.apim.swagger.APIManagerAdapter.getDateVersion(APIManagerAdapter.java:350)
        at com.axway.apim.swagger.APIManagerAdapter.hasAPIManagerVersion(APIManagerAdapter.java:327)
        at com.axway.apim.swagger.api.properties.outboundprofiles.OutboundProfile.<init>(OutboundProfile.java:60)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:119)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:270)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:277)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4014)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3005)
        at com.axway.apim.swagger.APIManagerAdapter.getAPIManagerAPI(APIManagerAdapter.java:407)
        at com.axway.apim.api.export.APIExportConfigAdapter.getExportAPI(APIExportConfigAdapter.java:124)
        at com.axway.apim.api.export.APIExportConfigAdapter.getAPIsToExport(APIExportConfigAdapter.java:116)
        at com.axway.apim.api.export.APIExportConfigAdapter.exportAPIs(APIExportConfigAdapter.java:72)
        at com.axway.apim.ExportApp.run(ExportApp.java:138)
        at com.axway.apim.ExportApp.main(ExportApp.java:36)
```
That makes the Log-Output pretty hard to read. As the Stack-Trace is considered as a warning, it should be removed.

**Comment by cwiechmann** [comment]
Will be changed in the next release.
