### ISSUE TITLE
[BUG] Unnecessary update of the Proxy leads to 403 for a published API

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apimanager-swagger-promote#257]
**Swagger-Promote version**
1.6.5

**API-Manager and Service-Pack Version**
7.7.20200130

**Expected behavior**
Properties that are not related to the API-Proxy itself (e.g. the Image, subscribed applications, etc.) should be possible even if the API is in state published.

**Actual behavior**
Swagger-Promote is trying to update the proxy which leads to a forbidden error.

**Log-Output in Debug**
```
------------------------------------------------------------------------
API-Manager Promote: 1.6.5 - I M P O R T

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote
------------------------------------------------------------------------

0      INFO  nvironmentProperties| Trying to load environment properties from file: env.properties ... not found.
5      INFO  nvironmentProperties| Loaded environment properties from file: env.api-env.properties.
3871   INFO  IImportConfigAdapter| Loading API-Definition from: https://raw.githubusercontent.com/cwiechmann/imagine-api-demo/master/api-definition/api-swagger-files/2-imagine-weather-api-2nd-version.json
4273   INFO          APIDefintion| Used the configured backendBasepath: 'http://192.168.65.1:8081/api/api/v1/weather' to adjust the Swagger definition.
4283   INFO  IImportConfigAdapter| Handling configured client-applications.
4342   INFO  IImportConfigAdapter| Found existing application: 'Test' (null) based on given name 'Test'
4368   INFO     APIManagerAdapter| API-Manager version is: 7.7.20200130
4371   INFO               Proxies| Sending request to find existing APIs: https://api-env:8075/api/portal/v1.3/proxies?field=path&op=eq&value=%2Fapi%2Fv1%2Fweather
4419   INFO               Proxies| Found existing API on path: '/api/v1/weather' (published) (ID: '3bdaea2a-176b-4ae5-a228-c346eeca6756')
4419   INFO               Proxies| Found: 1 exposed API(s)
5394   INFO     APIManagerAdapter| Strategy: Going to update existing API: Axway Imagine - Weather API (Version: 1.0.0)
5395   INFO     APIManagerAdapter| Recognized the following changes. Potentially Breaking: [] plus Non-Breaking: [applications, applicationQuota]
5396   INFO     APIManagerAdapter| Strategy: Update existing API, as all changes can be applied in current state.
5456   ERROR          RestAPICall| Response: 'HTTP/1.1 403 Forbidden'
5457   ERROR                  App| Cannot update API-Proxy.
com.axway.apim.lib.AppException: Cannot update API-Proxy.
        at com.axway.apim.actions.tasks.UpdateAPIProxy.execute(UpdateAPIProxy.java:55)
        at com.axway.apim.actions.UpdateExistingAPI.execute(UpdateExistingAPI.java:41)
        at com.axway.apim.swagger.APIManagerAdapter.applyChanges(APIManagerAdapter.java:188)
        at com.axway.apim.App.run(App.java:226)
        at com.axway.apim.App.main(App.java:50)
Caused by: com.axway.apim.lib.AppException: Unable to parse HTTP-Response
        at com.axway.apim.actions.rest.RestAPICall.parseResponse(RestAPICall.java:73)
        at com.axway.apim.actions.rest.PUTRequest.execute(PUTRequest.java:28)
        at com.axway.apim.actions.tasks.UpdateAPIProxy.execute(UpdateAPIProxy.java:53)
        ... 4 more
Caused by: com.axway.apim.lib.AppException: Unable to parse response
        at com.axway.apim.actions.tasks.UpdateAPIProxy.parseResponse(UpdateAPIProxy.java:80)
        at com.axway.apim.actions.rest.RestAPICall.parseResponse(RestAPICall.java:65)
        ... 6 more
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.http.client.methods.HttpEntityEnclosingRequestBase
        at com.axway.apim.actions.tasks.UpdateAPIProxy.parseResponse(UpdateAPIProxy.java:76)
        ... 7 more
```

**Comment by cwiechmann** [comment]
This will be fixed in version 1.6.7
