### ISSUE TITLE
[Organization] script fails with incorrect error message when organization doesn't exist

### ISSUE THREAD

**Issue by kervoaz** [Axway-API-Management-Plus/apimanager-swagger-promote#44]
Hello,

I receive error Can't import definition / Create BE-API. if the organization anme is incorrect or when the organization is not set for development.
May be a organization block could be added in swagger to check or create the orga if needed.
regards

**Comment by cwiechmann** [comment]
@kervoaz, good point and thanks for reporting. I'll create an Integration-Tests for this scenario and improve the error handling.

**Comment by cwiechmann** [comment]
@kervoaz, just to confirm. Are you getting this error? :

`com.axway.apim.lib.AppException: Can't import definition / Create BE-API.
	at com.axway.apim.actions.tasks.ImportBackendAPI.execute(ImportBackendAPI.java:42)
	at com.axway.apim.actions.CreateNewAPI.execute(CreateNewAPI.java:48)
......
Caused by: java.lang.IllegalArgumentException: Text may not be null
	at org.apache.http.util.Args.notNull(Args.java:54)
	at org.apache.http.entity.mime.content.StringBody.<init>(StringBody.java:155)
	at org.apache.http.entity.mime.MultipartEntityBuilder.addTextBody(MultipartEntityBuilder.java:153)
	at org.apache.http.entity.mime.MultipartEntityBuilder.addTextBody(MultipartEntityBuilder.java:158)
	at com.axway.apim.actions.tasks.ImportBackendAPI.importFromSwagger(ImportBackendAPI.java:93)
	at com.axway.apim.actions.tasks.ImportBackendAPI.execute(ImportBackendAPI.java:39)
	... 33 more`

**Comment by cwiechmann** [comment]
Now validating at configuration import, that the organization is known and has a development flag. If not, the tool fails with return-code: 57.
Also added an Integration-Test to validate the correct behavior.

The following message will be logged:
The given organization: '<GivenOrgName>' is either unknown or hasn't the Development flag.

**Comment by cwiechmann** [comment]
Just release this feature version 1.5.1
