### ISSUE TITLE
Unable to load image from absolute path

### ISSUE THREAD

**Issue by hakila** [Axway-API-Management-Plus/apimanager-swagger-promote#58]
I want to have image for my api. I placed the image at this location
```[XXXXX@YYYYY bin]$ ls -l /opt/axway/apiimages/basefareicon.png
-rw-r--r-- 1 apigtwsrv apigtwsrv 9654 May 20 18:53 /opt/axway/apiimages/basefareicon.png
```
in the config file i placed this value for image element and ran the script. Got the below error:
```
0      INFO                   App| ------------------------------------------------------------------------
0      INFO                   App| API-Manager Promote Version: 1.5.1
0      INFO                   App|
0      INFO                   App| To report issues or get help, please visit:
0      INFO                   App| https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote
0      INFO                   App| ------------------------------------------------------------------------
8      INFO  nvironmentProperties| Loaded environment properties from file: env.properties.
12     DEBUG    APIManagerAdapter| Logging in with User: 'apiadmin'
778    DEBUG    APIManagerAdapter| API-Manager version is: 7.7.0
881    DEBUG IImportConfigAdapter| Current path=/opt/axway/apimanager-swagger-promote-1.5.1
884    INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: '/opt/axway/pythonscripts/conf/apicreatejson/APITest.json' (relative path)
885    ERROR                  App| Cannot validate/fulfill configuration file.
com.axway.apim.lib.AppException: Cannot validate/fulfill configuration file.
        at com.axway.apim.swagger.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:156)
        at com.axway.apim.App.run(App.java:157)
        at com.axway.apim.App.main(App.java:42)
Caused by: com.axway.apim.lib.AppException: Can't read image-file: '/opt/axway/apiimages/basefareicon.png' from filesystem or classpath.
        at com.axway.apim.swagger.APIImportConfigAdapter.addImageContent(APIImportConfigAdapter.java:599)
        at com.axway.apim.swagger.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:142)
        ... 2 more
Caused by: java.lang.NullPointerException
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2314)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:2270)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2291)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:2246)
        at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:765)
        at com.axway.apim.swagger.APIImportConfigAdapter.addImageContent(APIImportConfigAdapter.java:595)
        ... 3 more
```
Image file existed but still getting error. Could you please suggest where I am doing wrong.

**Comment by cwiechmann** [comment]
@hakila, unfortunately you are stepping into issues, which has been identified recently and already fixed. See issue #52. The way how the image path is created has been changed plus a better error handlng. 
So, this issue is very likely to be fixed as well in the next release. The next release will come out very soon.

**Comment by hakila** [comment]
Thank you for the quick response. Latest release is 1.5.1. Approximately when is the next release date?

**Comment by hakila** [comment]
I tried with the snapshot. But image is still giving issue
"image": "/opt/axway/apiimages/basefareicon.png" This is what I had in config file. The file existed
 ls -l /opt/axway/apiimages/basefareicon.png
-rw-r--r-- 1 adm adm 9654 May 20 18:53 /opt/axway/apiimages/basefareicon.png
I got exception
951    DEBUG IImportConfigAdapter| Current path=/opt/axway/apimanager-swagger-promote-1.6-SNAPSHOT-1.5.1
954    INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: '/opt/axway/pythonscripts/conf/apicreatejson/TESTMinimumStayCategory06Rules_transformed.json' (relative path)
955    ERROR                  App| Image not found in filesystem ('/opt/axway/pythonscripts/conf/apiconfigjson/opt/axway/apiimages/basefareicon.png') or Classpath.
com.axway.apim.lib.AppException: Image not found in filesystem ('/opt/axway/pythonscripts/conf/apiconfigjson/opt/axway/apiimages/basefareicon.png') or Classpath.
        at com.axway.apim.swagger.APIImportConfigAdapter.addImageContent(APIImportConfigAdapter.java:598)
        at com.axway.apim.swagger.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:148)
        at com.axway.apim.App.run(App.java:157)
        at com.axway.apim.App.main(App.java:42)

Not sure where I am doing wrong. Is there specific format I have to give for image value?

**Comment by cwiechmann** [comment]
@hakila, it wasn't your fault at all. I realized I have never implemented support for absolute API-Image path. Now it's and will be supported with the next release. (early next week)
Thanks for reporting!

**Comment by cwiechmann** [comment]
Has been released with version 1.5.2.

**Comment by hakila** [comment]
How do I get the 1.5.2 release? Please direct me to the page.

**Comment by cwiechmann** [comment]
You find it in the releases.

**Comment by hakila** [comment]
These swagger promote scripts support 7.5.3 SP6 apimanager, gateway ? Please let me know.
