### ISSUE TITLE
NPE while managing CLientApps on Unpublished API

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apimanager-swagger-promote#82]
When an API-Config is defining an API as Unpublished, but still has some Applications configured, under some circumstances the following NPE may be thrown:
```
4909   ERROR                  App|
java.lang.NullPointerException
        at com.axway.apim.actions.tasks.ManageClientApps.hasClientAppPermission(ManageClientApps.java:96)
        at com.axway.apim.actions.tasks.ManageClientApps.execute(ManageClientApps.java:56)
        at com.axway.apim.actions.UpdateExistingAPI.execute(UpdateExistingAPI.java:55)
        at com.axway.apim.swagger.APIManagerAdapter.applyChanges(APIManagerAdapter.java:155)
        at com.axway.apim.App.run(App.java:160)
        at com.axway.apim.App.main(App.java:42)
```
This ccenario needs an integration tests + fix.

**Comment by cwiechmann** [comment]
Unable to reproduce anymore.
